---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent
  namespace: vault-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-agent-sa
  namespace: vault-agent
  annotations:
    kubernetes.io/service-account.name: vault-agent
type: kubernetes.io/service-account-token
